# Tensor
张量是一种特殊的数据结构，与数组和矩阵非常相似。
在PyTorch中，我们使用张量来编码模型的输入和输出，以及模型的参数。

In [1]:
# 导包
import torch
import numpy as np

## 初始化张量

In [3]:
# 张量可以直接从数据中创建。数据类型是自动推断的。
data = [[1,2],[3,4]] #list
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
# 从numpy数组创建张量
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
# 从其他张量创建，新张量保留参数张量的属性（形状、数据类型）
x_ones = torch.ones_like(x_data) # 保留数据类型
x_rand = torch.rand_like(x_data,dtype=torch.float) # 覆盖数据类型
x_ones, x_rand

(tensor([[1, 1],
         [1, 1]]),
 tensor([[0.2201, 0.9070],
         [0.5551, 0.7253]]))

In [11]:
# 指定张量维度
# shape 是张量维度的元组。在下面的函数中，它决定了输出张量的维度。
shape = (2,3,)
rand_tensor = torch.rand(shape)
rand_tensor

tensor([[0.9823, 0.7189, 0.4722],
        [0.9236, 0.4351, 0.4800]])

## 张量的属性

In [12]:
# 张量属性描述了它们的形状、数据类型、存储它们的设备
tensor = torch.rand(3,4)
tensor.shape, tensor.dtype, tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

## 张量操作

In [13]:
# 张量操作包括算术，线性代数，矩阵操作(转置，索引，切片)
# 默认情况下，张量是在CPU上创建的。
# 我们需要使用.to方法显式地将张量移动到GPU(在检查GPU可用性之后)。
# 从时间和内存方面来说，在设备之间复制大型张量是非常昂贵的
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [17]:
# 一些操作上，tensor和numpy数组很类似
# 索引和切片
tensor = torch.ones(4, 4)
tensor[0] # 首行
tensor[:,0] # 首列
tensor[...,-1] # 最后一列

tensor([1., 1., 1., 1.])

In [18]:
# 连接张量
# 可以使用cat沿给定维度连接一系列张量
t1 = torch.cat([tensor,tensor,tensor],dim=1) # dim=1按列连接
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
# 算术运算  
# 张量间的矩阵乘法，y1, y2, y3 将具有相同的值
# matmul内积
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
y1, y2, y3
torch.matmul(tensor, tensor.T, out=y3)

# 元素乘积
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
z1, z2, z3

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [24]:
# 单元素张量
# 通过张量的所有值聚合为一个常量值，使用item()
agg = tensor.sum()
agg_item = agg.item()
agg, agg_item, type(agg_item) 

(tensor(16.), 16.0, float)

In [28]:
# in-place操作
# 将结果直接存储到操作数中的操作成为in-place操作，即直接对原视图进行操作改变
# 这些操作用_后缀表示
tensor.add_(5)
tensor
tensor.copy_(tensor)
tensor
# in-place操作可以节省一些内存，但在计算导数时可能会出现问题，因为会立即丢失历史记录
# 因此，不鼓励使用它们。

tensor([[21., 21., 21., 21.],
        [21., 21., 21., 21.],
        [21., 21., 21., 21.],
        [21., 21., 21., 21.]])

## 与numpy的关联

In [33]:
# CPU 和 NumPy 数组上的张量可以共享它们的底层内存位置，改变一个会改变另一个。
# tensor to numpy数组
t = torch.ones(5)
n = t.numpy()
t, n
type(t),type(n)

# 改变张量，数组也会变化
t.add_(1)
t,n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [36]:
# numpy数组 to tensor
n = np.ones(5)
t = torch.from_numpy(n)
n, t

# NumPy 数组的变化反映在张量中
np.add(n, 1, out = n)
t, n


(tensor([2., 2., 2., 2., 2.], dtype=torch.float64),
 array([2., 2., 2., 2., 2.]))